# This workflow builds and pushes the Docker image for the OJP server.
name: OJP Server Docker Image Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Additional Docker image tag'
        required: false
        default: 'latest'
      repository:
        description: 'Repository name'
        required: true
        default: 'rrobetti'
jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'
          cache: maven

      - name: Get project version
        id: get_version
        run: |
           VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
           echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
           echo "Project version: $VERSION"

      - name: Build and push Docker image
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ${{ github.event.inputs.repository }}
        run: |
            mvn install -N -DskipTests
            mvn install -pl ojp-grpc-commons -DskipTests
            mvn compile jib:build -pl ojp-server \
            -Djib.to.auth.username="${DOCKERHUB_USER}" \
            -Djib.to.auth.password="${DOCKERHUB_TOKEN}" \
            -Djib.to.image="${DOCKERHUB_REPO}/ojp:${{ steps.get_version.outputs.VERSION }}" \
            -Djib.to.tags="${{ steps.get_version.outputs.VERSION }}" \
            -Djib.container.mainClass="org.openjproxy.grpc.server.GrpcServer" \
            -Djib.container.ports=1059